# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: [--autofix, --indent, '4']
    -   id: check-shebang-scripts-are-executable

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --preserve-quotes, --indent, '4']
    -   id: pretty-format-toml
        args: [--autofix]

-   repo: local
    hooks:
    -   id: black
        name: Formatting code with Black
        entry: pipenv run black
        language: system
        types: [python]
    -   id: isort
        name: Sorting code imports with isort
        entry: pipenv run isort
        language: system
        types: [python]
    -   id: mypy
        name: Checking types with MyPy
        entry: pipenv run mypy
        language: system
        types: [python]
    -   id: pylint
        name: Checking linting with Pylint
        entry: pipenv run pylint
        language: system
        types: [python]
    -   id: pytest
        name: Running tests with Pytest
        entry: pipenv run pytest
        always_run: true
        pass_filenames: false
        language: system

default_language_version:
    python: python3.10
