[tool.black]
quiet = true
preview = true

[tool.isort]
profile = "black"

[tool.pylint]
disable = [
    "R0903", # too-few-public-methods
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

addopts = "-vv -x --cov"
